server:
  #  port: 3306
  port: 8081

spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost/db_users
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update